### ISSUE TITLE
Constitution improvements (meta-issue)

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#119]
In #112, it became clear that there were too many issues raised with the constitution to address in a single pull request. Hence, I merged that PR into a separate branch such that we can address issues one-by-one. 

Here is a list of known issues/requests that we've seen thus far for the constitution. For each one, feel free to make a single issue to track it if it requires extensive discussion.
- [x] Fix keypair in metadata from `hidden: true` to `status: hidden`
- [x] Wording: should we say "Director of Women in CS" or "Chair of the WiCS Committee"?
- [x] Should an individual be able to serve as Chair for two or more consecutive terms?
- [x] Which committee members can be on co-op?
- [x] What do we do when no returning member wishes to be Chair? (PR #146)
- [x] What do we do when there are too many interested and qualified returning and new committee members? (PR #146)
- [x] Do we need "dissolution" and "acceptable use of committee resources" sections? (PR #147)
- [x] Add a formal procedure for choosing communication and organizational technologies (PR #137)
- [x] Add more detail in the interview procedure (PR #146)
- [x] Add a responsibility for all committee members to identify when others are falling behind on their responsibilities and a suggested script/procedure to ensure they get help (PR #143)
- [x] Additional value: Accountability
- [x] Additional value: Consensus-building
- [x] Add a section on volunteers and require the next term's first volunteer meeting to be planned before interviews begin (PR #144)
- [x] Add responsibility for chair: resolving internal committee disputes (PR #143)
- [x] Update value: Technical Excellence (PR #148)
- [x] What happens when a committee member resigns? Should there be a procedure for removing a committee member? (PR #152)
- [x] How do we enforce this document?
- [x] Expand scope of purpose and vision: [change 'in' to 'interested in'](https://github.com/wics-uw/website/commit/2e27c3bdede9b86bbba07137c63062a9a10d082c#diff-74953e3a91c542726ee6570d6cc6c8f9R17) (PR #151)
- [x] Add Fatema's responsibility for Chair (PR #153)

Feel free to suggest more in comments, I will update this issue as progress is made.

**Comment by fboxwala** [comment]
re. Director vs. Chair from Jo:

_HI Fatema,
The name of WICS is still the Women in Computer Science Committee, and I’m currently the chair of that committee.  What is new is that the School started a new Director-level position in its administration:  the Director of Women in Computer Science, and I currently served in that role as well.
I expect that it will normally be the case that the Director of Women in Computer Science will chair the WICS committee, but they are technically two different roles._

I think the person we want to refer to is still chair of the committee. What think?

**Comment by ehashman** [comment]
Agreed, re: Chair Fatema. Let's change all instances of Director to Chair.

**Comment by ehashman** [comment]
> Do we need "dissolution" and "acceptable use of committee resources" sections?

I feel like "no" for the dissolution section for now, and that we should have an "acceptance use of resources" section.

**Comment by ehashman** [comment]
Re: enforcement, most constitutions I've looked at don't have a specific clause, so I'll mark that as done.

I am going to address feedback in #146 to hopefully make it mergeable, submit a PR regarding committee members leaving (or their removal), and then my hope is that this can be read through over the weekend and can be ratified during the next meeting.

**Comment by fboxwala** [comment]
Wanted to add a responsibility for chair:

"To work with the secretary to ensure that members are able to complete their assigned tasks, and that the committee functions cohesively"

**Comment by ehashman** [comment]
Okay, so we're just waiting on the decisions on the two different wordings in #146. Once that's merged, this issue will be closed and we can make a pull request for the entire constitution into master.
